es:
  uri: http://opensearch-cluster-master:9200
  sslSkipVerify: true # We are using plain HTTP internally, but good practice if mixed

serviceMonitor:
  enabled: true
  namespace: opensearch
  labels:
    release: prometheus # Match the prometheus operator selector if needed

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

