apiVersion: v1
kind: Secret
metadata:
  name: mysqld-exporter-config
  namespace: mysql
type: Opaque
stringData:
  .my.cnf: |
    [client]
    user=${MYSQL_USER}
    password=${MYSQL_PASSWORD}
    host=127.0.0.1
    port=3306

