apiVersion: v1
kind: Secret
metadata:
  name: mysql-s3-backup-credentials
  namespace: mysql
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
  AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
