apiVersion: v1
kind: Secret
metadata:
  name: mysql-cluster-secrets
  namespace: mysql
type: Opaque
stringData:
  ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
  DATABASE: "${MYSQL_DATABASE}"
  USER: "${MYSQL_USER}"
  PASSWORD: "${MYSQL_PASSWORD}"
